AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'bin/bundle'
    - 'bin/yarn'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 120

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
