AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'bin/bundle'
    - 'bin/yarn'
    - 'db/schema.rb'
    - 'lib/tasks/cucumber.rake'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'config/**/*'
    - 'spec/**/*'

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: "double_quotes"
