 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/sensors", type: :request do
  
  # Sensor. As you add validations to Sensor, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Sensor.create! valid_attributes
      get sensors_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      sensor = Sensor.create! valid_attributes
      get sensor_url(sensor)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_sensor_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      sensor = Sensor.create! valid_attributes
      get edit_sensor_url(sensor)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Sensor" do
        expect {
          post sensors_url, params: { sensor: valid_attributes }
        }.to change(Sensor, :count).by(1)
      end

      it "redirects to the created sensor" do
        post sensors_url, params: { sensor: valid_attributes }
        expect(response).to redirect_to(sensor_url(Sensor.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Sensor" do
        expect {
          post sensors_url, params: { sensor: invalid_attributes }
        }.to change(Sensor, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post sensors_url, params: { sensor: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested sensor" do
        sensor = Sensor.create! valid_attributes
        patch sensor_url(sensor), params: { sensor: new_attributes }
        sensor.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the sensor" do
        sensor = Sensor.create! valid_attributes
        patch sensor_url(sensor), params: { sensor: new_attributes }
        sensor.reload
        expect(response).to redirect_to(sensor_url(sensor))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        sensor = Sensor.create! valid_attributes
        patch sensor_url(sensor), params: { sensor: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested sensor" do
      sensor = Sensor.create! valid_attributes
      expect {
        delete sensor_url(sensor)
      }.to change(Sensor, :count).by(-1)
    end

    it "redirects to the sensors list" do
      sensor = Sensor.create! valid_attributes
      delete sensor_url(sensor)
      expect(response).to redirect_to(sensors_url)
    end
  end
end
